namespace ServiceReference1
{
    using System.Runtime.Serialization;
    using System;
    using System.ServiceModel;
    using System.ServiceModel.Description;

    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------





    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Insurer", Namespace = "http://schemas.datacontract.org/2004/07/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InsurerDoc))]
    public partial class Insurer : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Nullable<int> CodeSMOField;

        private string DatBeginPolisField;

        private string DatEndPolisField;

        private string Num_PolisField;

        private string OGRNSMOField;

        private string Ser_PolisField;

        private int TypePolisField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodeSMO
        {
            get
            {
                return this.CodeSMOField;
            }
            set
            {
                this.CodeSMOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatBeginPolis
        {
            get
            {
                return this.DatBeginPolisField;
            }
            set
            {
                this.DatBeginPolisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatEndPolis
        {
            get
            {
                return this.DatEndPolisField;
            }
            set
            {
                this.DatEndPolisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_Polis
        {
            get
            {
                return this.Num_PolisField;
            }
            set
            {
                this.Num_PolisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OGRNSMO
        {
            get
            {
                return this.OGRNSMOField;
            }
            set
            {
                this.OGRNSMOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ser_Polis
        {
            get
            {
                return this.Ser_PolisField;
            }
            set
            {
                this.Ser_PolisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypePolis
        {
            get
            {
                return this.TypePolisField;
            }
            set
            {
                this.TypePolisField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InsurerDoc", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class InsurerDoc : Insurer
    {

        private string ENPField;

        private System.Nullable<int> LPUAUTOField;

        private System.Nullable<System.DateTime> LPUDTField;

        private string MOField;

        private string SNILSField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENP
        {
            get
            {
                return this.ENPField;
            }
            set
            {
                this.ENPField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LPUAUTO
        {
            get
            {
                return this.LPUAUTOField;
            }
            set
            {
                this.LPUAUTOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LPUDT
        {
            get
            {
                return this.LPUDTField;
            }
            set
            {
                this.LPUDTField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MO
        {
            get
            {
                return this.MOField;
            }
            set
            {
                this.MOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SNILS
        {
            get
            {
                return this.SNILSField;
            }
            set
            {
                this.SNILSField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InsurerFIO", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class InsurerFIO : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Nullable<int> CodeSMOField;

        private string DatBeginPolisField;

        private string DatEndPolisField;

        private System.Nullable<System.DateTime> DrField;

        private string FamField;

        private string ImField;

        private string Num_PolisField;

        private string OGRNSMOField;

        private string OtField;

        private string Ser_PolisField;

        private int TypePolisField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodeSMO
        {
            get
            {
                return this.CodeSMOField;
            }
            set
            {
                this.CodeSMOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatBeginPolis
        {
            get
            {
                return this.DatBeginPolisField;
            }
            set
            {
                this.DatBeginPolisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatEndPolis
        {
            get
            {
                return this.DatEndPolisField;
            }
            set
            {
                this.DatEndPolisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dr
        {
            get
            {
                return this.DrField;
            }
            set
            {
                this.DrField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fam
        {
            get
            {
                return this.FamField;
            }
            set
            {
                this.FamField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Im
        {
            get
            {
                return this.ImField;
            }
            set
            {
                this.ImField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_Polis
        {
            get
            {
                return this.Num_PolisField;
            }
            set
            {
                this.Num_PolisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OGRNSMO
        {
            get
            {
                return this.OGRNSMOField;
            }
            set
            {
                this.OGRNSMOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ot
        {
            get
            {
                return this.OtField;
            }
            set
            {
                this.OtField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ser_Polis
        {
            get
            {
                return this.Ser_PolisField;
            }
            set
            {
                this.Ser_PolisField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypePolis
        {
            get
            {
                return this.TypePolisField;
            }
            set
            {
                this.TypePolisField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IInsurer")]
    public interface IInsurer
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IInsurer/GetInsurer", ReplyAction = "http://tempuri.org/IInsurer/GetInsurerResponse")]
        Insurer GetInsurer(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IInsurer/GetInsurer", ReplyAction = "http://tempuri.org/IInsurer/GetInsurerResponse")]
        System.Threading.Tasks.Task<Insurer> GetInsurerAsync(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IInsurer/GetInsurerFIO", ReplyAction = "http://tempuri.org/IInsurer/GetInsurerFIOResponse")]
        InsurerFIO GetInsurerFIO(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IInsurer/GetInsurerFIO", ReplyAction = "http://tempuri.org/IInsurer/GetInsurerFIOResponse")]
        System.Threading.Tasks.Task<InsurerFIO> GetInsurerFIOAsync(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IInsurer/GetInsurerDOC", ReplyAction = "http://tempuri.org/IInsurer/GetInsurerDOCResponse")]
        InsurerDoc GetInsurerDOC(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IInsurer/GetInsurerDOC", ReplyAction = "http://tempuri.org/IInsurer/GetInsurerDOCResponse")]
        System.Threading.Tasks.Task<InsurerDoc> GetInsurerDOCAsync(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInsurerChannel : IInsurer, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsurerClient : System.ServiceModel.ClientBase<IInsurer>, IInsurer
    {

        public InsurerClient()
        {
        }

        public InsurerClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public InsurerClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public InsurerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public InsurerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public Insurer GetInsurer(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual)
        {
            return base.Channel.GetInsurer(TypePolis, Ser_Polis, Num_Polis, DateActual);
        }

        public System.Threading.Tasks.Task<Insurer> GetInsurerAsync(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual)
        {
            return base.Channel.GetInsurerAsync(TypePolis, Ser_Polis, Num_Polis, DateActual);
        }

        public InsurerFIO GetInsurerFIO(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual)
        {
            return base.Channel.GetInsurerFIO(TypePolis, Ser_Polis, Num_Polis, DateActual);
        }

        public System.Threading.Tasks.Task<InsurerFIO> GetInsurerFIOAsync(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual)
        {
            return base.Channel.GetInsurerFIOAsync(TypePolis, Ser_Polis, Num_Polis, DateActual);
        }

        public InsurerDoc GetInsurerDOC(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual)
        {
            return base.Channel.GetInsurerDOC(TypePolis, Ser_Polis, Num_Polis, DateActual);
        }

        public System.Threading.Tasks.Task<InsurerDoc> GetInsurerDOCAsync(int TypePolis, string Ser_Polis, string Num_Polis, string DateActual)
        {
            return base.Channel.GetInsurerDOCAsync(TypePolis, Ser_Polis, Num_Polis, DateActual);
        }
    }
}
